POST http://localhost:3000/post 
content-type: application/json

{
    "title": "Test post",
    "author": "Filip",
    "content": "Content posta",
    "isPublished": true,
    "upvotes": 1
}

###

GET  http://localhost:3000/posts
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST  http://localhost:3000/upvote/1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}