@host = http://127.0.0.1:3000

GET {{host}}/api/task

###

POST {{host}}/api/task
Content-Type: application/json

{
  "id": 1,
  "title": "Test",
  "desc": "Przykładowa notatka",
  "category": "Ogólne"
}

###

POST {{host}}/api/task/backup
Content-Type: application/json

{
  "notes": [
    {
      "id": 1,
      "title": "Backup test",
      "desc": "Treść notatki",
      "category": "Ogólne"
    }
  ]
}

###

PATCH {{host}}/api/task/1
Content-Type: application/json

{
  "title": "Zmieniony tytuł",
  "desc": "Zmieniona treść",
  "category": "Ogólne"
}

###

DELETE {{host}}/api/task/1

###

DELETE {{host}}/api/task
